"""initial migration

Revision ID: 4158988ee251
Revises: 
Create Date: 2019-03-27 17:52:13.459715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4158988ee251'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('nickname', sa.String(length=24), nullable=False, comment='昵称'),
    sa.Column('email', sa.String(length=24), nullable=False, comment='邮箱'),
    sa.Column('auth', sa.SmallInteger(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False, comment='密码'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
