"""add auth comment

Revision ID: 5436b8287291
Revises: 4158988ee251
Create Date: 2019-03-27 18:23:02.387466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5436b8287291'
down_revision = '4158988ee251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'auth',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='权限，超级管理员或普通用户',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'auth',
               existing_type=mysql.SMALLINT(display_width=6),
               comment=None,
               existing_comment='权限，超级管理员或普通用户',
               existing_nullable=True)
    # ### end Alembic commands ###
